In [1]:
pip install pandas

Requirement already satisfied: pandas in /Users/elmojuanara/opt/anaconda3/lib/python3.9/site-packages (1.4.4)
Requirement already satisfied: python-dateutil>=2.8.1 in /Users/elmojuanara/opt/anaconda3/lib/python3.9/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/elmojuanara/opt/anaconda3/lib/python3.9/site-packages (from pandas) (2022.1)
Requirement already satisfied: numpy>=1.18.5 in /Users/elmojuanara/opt/anaconda3/lib/python3.9/site-packages (from pandas) (1.21.5)
Requirement already satisfied: six>=1.5 in /Users/elmojuanara/opt/anaconda3/lib/python3.9/site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd

In [2]:
so_data = pd.read_csv('survey_results_public.csv')

In [3]:
so_data

,ResponseId,MainBranch,Employment,Country,US_State,UK_Country,EdLevel,Age1stCode,LearnCode,YearsCode,...,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,SurveyLength,SurveyEase,ConvertedCompYearly
0,1,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Slovakia,NaN,NaN,"Secondary school (e.g. American high school, G...",18 - 24 years,Coding Bootcamp;Other online resources (ex: vi...,NaN,...,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,62268.0
1,2,I am a student who is learning to code,"Student, full-time",Netherlands,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",7,...,18-24 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,NaN
2,3,"I am not primarily a developer, but I write co...","Student, full-time",Russian Federation,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",NaN,...,18-24 years old,Man,No,Prefer not to say,Prefer not to say,None of the above,None of the above,Appropriate in length,Easy,NaN
3,4,I am a developer by profession,Employed full-time,Austria,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",11 - 17 years,NaN,NaN,...,35-44 years old,Man,No,Straight / Heterosexual,White or of European descent,I am deaf / hard of hearing,NaN,Appropriate in length,Neither easy nor difficult,NaN
4,5,I am a developer by profession,"Independent contractor, freelancer, or self-em...",United Kingdom of Great Britain and Northern I...,NaN,England,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",5 - 10 years,Friend or family member,17,...,25-34 years old,Man,No,NaN,White or of European descent,None of the above,NaN,Appropriate in length,Easy,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83434,83435,I am a developer by profession,Employed full-time,United States of America,Texas,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",6,...,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,I have a concentration and/or memory disorder ...,Appropriate in length,Easy,160500.0
83435,83436,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Benin,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",4,...,18-24 years old,Man,No,Straight / Heterosexual,Black or of African descent,None of the above,None of the above,Appropriate in length,Easy,3960.0
83436,83437,I am a developer by profession,Employed full-time,United States of America,New Jersey,NaN,"Secondary school (e.g. American high school, G...",11 - 17 years,School,10,...,25-34 years old,Man,No,NaN,White or of European descent,None of the above,None of the above,Appropriate in length,Neither easy nor difficult,90000.0
83437,83438,I am a developer by profession,Employed full-time,Canada,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,Online Courses or Certification;Books / Physic...,5,...,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,I have a mood or emotional disorder (e.g. depr...,Appropriate in length,Neither easy nor difficult,816816.0
83438,83439,I am a developer by profession,Employed full-time,Brazil,NaN,NaN,"Professional degree (JD, MD, etc.)",11 - 17 years,School,14,...,18-24 years old,Man,No,Straight / Heterosexual,Hispanic or Latino/a/x,None of the above,None of the above,Appropriate in length,Easy,21168.0

In [4]:
so_data.head()

,ResponseId,MainBranch,Employment,Country,US_State,UK_Country,EdLevel,Age1stCode,LearnCode,YearsCode,...,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,SurveyLength,SurveyEase,ConvertedCompYearly
0,1,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Slovakia,NaN,NaN,"Secondary school (e.g. American high school, G...",18 - 24 years,Coding Bootcamp;Other online resources (ex: vi...,NaN,...,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,62268.0
1,2,I am a student who is learning to code,"Student, full-time",Netherlands,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",7,...,18-24 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,NaN
2,3,"I am not primarily a developer, but I write co...","Student, full-time",Russian Federation,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",NaN,...,18-24 years old,Man,No,Prefer not to say,Prefer not to say,None of the above,None of the above,Appropriate in length,Easy,NaN
3,4,I am a developer by profession,Employed full-time,Austria,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",11 - 17 years,NaN,NaN,...,35-44 years old,Man,No,Straight / Heterosexual,White or of European descent,I am deaf / hard of hearing,NaN,Appropriate in length,Neither easy nor difficult,NaN
4,5,I am a developer by profession,"Independent contractor, freelancer, or self-em...",United Kingdom of Great Britain and Northern I...,NaN,England,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",5 - 10 years,Friend or family member,17,...,25-34 years old,Man,No,NaN,White or of European descent,None of the above,NaN,Appropriate in length,Easy,NaN

In [5]:
so_data.head(10)

,ResponseId,MainBranch,Employment,Country,US_State,UK_Country,EdLevel,Age1stCode,LearnCode,YearsCode,...,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,SurveyLength,SurveyEase,ConvertedCompYearly
0,1,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Slovakia,NaN,NaN,"Secondary school (e.g. American high school, G...",18 - 24 years,Coding Bootcamp;Other online resources (ex: vi...,NaN,...,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,62268.0
1,2,I am a student who is learning to code,"Student, full-time",Netherlands,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",7,...,18-24 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,NaN
2,3,"I am not primarily a developer, but I write co...","Student, full-time",Russian Federation,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",NaN,...,18-24 years old,Man,No,Prefer not to say,Prefer not to say,None of the above,None of the above,Appropriate in length,Easy,NaN
3,4,I am a developer by profession,Employed full-time,Austria,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",11 - 17 years,NaN,NaN,...,35-44 years old,Man,No,Straight / Heterosexual,White or of European descent,I am deaf / hard of hearing,NaN,Appropriate in length,Neither easy nor difficult,NaN
4,5,I am a developer by profession,"Independent contractor, freelancer, or self-em...",United Kingdom of Great Britain and Northern I...,NaN,England,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",5 - 10 years,Friend or family member,17,...,25-34 years old,Man,No,NaN,White or of European descent,None of the above,NaN,Appropriate in length,Easy,NaN
5,6,I am a student who is learning to code,"Student, part-time",United States of America,Georgia,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",NaN,...,18-24 years old,Prefer not to say,No,Straight / Heterosexual,Prefer not to say,None of the above,I have a concentration and/or memory disorder ...,Too long,Neither easy nor difficult,NaN
6,7,I code primarily as a hobby,I prefer not to say,United States of America,New Hampshire,NaN,"Secondary school (e.g. American high school, G...",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",3,...,Prefer not to say,Prefer not to say,No,NaN,I don't know,None of the above,None of the above,Appropriate in length,Neither easy nor difficult,NaN
7,8,I am a student who is learning to code,"Student, full-time",Malaysia,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,School;Online Courses or Certification,4,...,18-24 years old,Woman,No,Straight / Heterosexual,White or of European descent;Multiracial;South...,None of the above,None of the above,Appropriate in length,Easy,NaN
8,9,I am a developer by profession,Employed part-time,India,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",18 - 24 years,Coding Bootcamp,6,...,25-34 years old,Man,No,NaN,South Asian,NaN,I have a concentration and/or memory disorder ...,Appropriate in length,Easy,NaN
9,10,I am a developer by profession,Employed full-time,Sweden,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",11 - 17 years,School,7,...,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Neither easy nor difficult,51552.0

In [6]:
so_data.head(3)

,ResponseId,MainBranch,Employment,Country,US_State,UK_Country,EdLevel,Age1stCode,LearnCode,YearsCode,...,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,SurveyLength,SurveyEase,ConvertedCompYearly
0,1,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Slovakia,NaN,NaN,"Secondary school (e.g. American high school, G...",18 - 24 years,Coding Bootcamp;Other online resources (ex: vi...,NaN,...,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,62268.0
1,2,I am a student who is learning to code,"Student, full-time",Netherlands,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",7,...,18-24 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,NaN
2,3,"I am not primarily a developer, but I write co...","Student, full-time",Russian Federation,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",NaN,...,18-24 years old,Man,No,Prefer not to say,Prefer not to say,None of the above,None of the above,Appropriate in length,Easy,NaN

In [7]:
so_data.tail()

,ResponseId,MainBranch,Employment,Country,US_State,UK_Country,EdLevel,Age1stCode,LearnCode,YearsCode,...,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,SurveyLength,SurveyEase,ConvertedCompYearly
83434,83435,I am a developer by profession,Employed full-time,United States of America,Texas,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",6,...,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,I have a concentration and/or memory disorder ...,Appropriate in length,Easy,160500.0
83435,83436,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Benin,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",4,...,18-24 years old,Man,No,Straight / Heterosexual,Black or of African descent,None of the above,None of the above,Appropriate in length,Easy,3960.0
83436,83437,I am a developer by profession,Employed full-time,United States of America,New Jersey,NaN,"Secondary school (e.g. American high school, G...",11 - 17 years,School,10,...,25-34 years old,Man,No,NaN,White or of European descent,None of the above,None of the above,Appropriate in length,Neither easy nor difficult,90000.0
83437,83438,I am a developer by profession,Employed full-time,Canada,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,Online Courses or Certification;Books / Physic...,5,...,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,I have a mood or emotional disorder (e.g. depr...,Appropriate in length,Neither easy nor difficult,816816.0
83438,83439,I am a developer by profession,Employed full-time,Brazil,NaN,NaN,"Professional degree (JD, MD, etc.)",11 - 17 years,School,14,...,18-24 years old,Man,No,Straight / Heterosexual,Hispanic or Latino/a/x,None of the above,None of the above,Appropriate in length,Easy,21168.0

In [8]:
so_data.head(10)

,ResponseId,MainBranch,Employment,Country,US_State,UK_Country,EdLevel,Age1stCode,LearnCode,YearsCode,...,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,SurveyLength,SurveyEase,ConvertedCompYearly
0,1,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Slovakia,NaN,NaN,"Secondary school (e.g. American high school, G...",18 - 24 years,Coding Bootcamp;Other online resources (ex: vi...,NaN,...,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,62268.0
1,2,I am a student who is learning to code,"Student, full-time",Netherlands,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",7,...,18-24 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,NaN
2,3,"I am not primarily a developer, but I write co...","Student, full-time",Russian Federation,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",NaN,...,18-24 years old,Man,No,Prefer not to say,Prefer not to say,None of the above,None of the above,Appropriate in length,Easy,NaN
3,4,I am a developer by profession,Employed full-time,Austria,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",11 - 17 years,NaN,NaN,...,35-44 years old,Man,No,Straight / Heterosexual,White or of European descent,I am deaf / hard of hearing,NaN,Appropriate in length,Neither easy nor difficult,NaN
4,5,I am a developer by profession,"Independent contractor, freelancer, or self-em...",United Kingdom of Great Britain and Northern I...,NaN,England,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",5 - 10 years,Friend or family member,17,...,25-34 years old,Man,No,NaN,White or of European descent,None of the above,NaN,Appropriate in length,Easy,NaN
5,6,I am a student who is learning to code,"Student, part-time",United States of America,Georgia,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",NaN,...,18-24 years old,Prefer not to say,No,Straight / Heterosexual,Prefer not to say,None of the above,I have a concentration and/or memory disorder ...,Too long,Neither easy nor difficult,NaN
6,7,I code primarily as a hobby,I prefer not to say,United States of America,New Hampshire,NaN,"Secondary school (e.g. American high school, G...",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",3,...,Prefer not to say,Prefer not to say,No,NaN,I don't know,None of the above,None of the above,Appropriate in length,Neither easy nor difficult,NaN
7,8,I am a student who is learning to code,"Student, full-time",Malaysia,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,School;Online Courses or Certification,4,...,18-24 years old,Woman,No,Straight / Heterosexual,White or of European descent;Multiracial;South...,None of the above,None of the above,Appropriate in length,Easy,NaN
8,9,I am a developer by profession,Employed part-time,India,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",18 - 24 years,Coding Bootcamp,6,...,25-34 years old,Man,No,NaN,South Asian,NaN,I have a concentration and/or memory disorder ...,Appropriate in length,Easy,NaN
9,10,I am a developer by profession,Employed full-time,Sweden,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",11 - 17 years,School,7,...,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Neither easy nor difficult,51552.0

In [10]:
so_data.shape

(83439, 48)

In [31]:
so_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83439 entries, 0 to 83438
Data columns (total 47 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   ResponseId                    83439 non-null  int64
 1   MainBranch                    83439 non-null  object
 2   Employment                    83323 non-null  object
 3   Country                       83439 non-null  object
 4   US_State                      14920 non-null  object
 5   UK_Country                    4418 non-null   object
 6   EdLevel                       83126 non-null  object
 7   Age1stCode                    83243 non-null  object
 8   LearnCode                     82963 non-null  object
 9   YearsCode                     81641 non-null  object
 10  YearsCodePro                  61216 non-null  object
 11  DevType                       66484 non-null  object
 12  OrgSize                       60726 non-null  object
 13  Currency                      61080 non-null  object
 14  CompFreq                      52150 non-null  object
 15  LanguageHaveWorkedWith        82357 non-null  object
 16  LanguageWantToWorkWith        76821 non-null  object
 17  DatabaseHaveWorkedWith        69546 non-null  object
 18  DatabaseWantToWorkWith        58299 non-null  object
 19  PlatformHaveWorkedWith        52135 non-null  object
 20  PlatformWantToWorkWith        41619 non-null  object
 21  WebframeHaveWorkedWith        61707 non-null  object
 22  WebframeWantToWorkWith        52095 non-null  object
 23  MiscTechHaveWorkedWith        47055 non-null  object
 24  MiscTechWantToWorkWith        38021 non-null  object
 25  ToolsTechHaveWorkedWith       72537 non-null  object
 26  ToolsTechWantToWorkWith       65480 non-null  object
 27  NEWCollabToolsHaveWorkedWith  81234 non-null  object
 28  NEWCollabToolsWantToWorkWith  73022 non-null  object
 29  OpSys                         83294 non-null  object
 30  NEWStuck                      83052 non-null  object
 31  NEWSOSites                    83171 non-null  object
 32  SOVisitFreq                   82413 non-null  object
 33  SOAccount                     82525 non-null  object
 34  SOPartFreq                    67553 non-null  object
 35  SOComm                        82319 non-null  object
 36  NEWOtherComms                 82828 non-null  object
 37  Age                           82407 non-null  object
 38  Gender                        82286 non-null  object
 39  Trans                         80678 non-null  object
 40  Sexuality                     73366 non-null  object
 41  Ethnicity                     79464 non-null  object
 42  Accessibility                 77603 non-null  object
 43  MentalHealth                  76920 non-null  object
 44  SurveyLength                  81711 non-null  object
 45  SurveyEase                    81948 non-null  object
 46  ConvertedCompYearly           46844 non-null  float64
dtypes: float64(1), int64(1), object(45)
memory usage: 29.9+ MB

In [12]:
so_data.duplicated().sum()

0

In [13]:
sample_data = [['Jack', 10],['Jill',11],['Harry',12],['Vin',13],['Jake',14],['Jake',14],['Jake',14]]

In [14]:
sample_df = pd.DataFrame(sample_data, columns = ['Name', 'Age'])
sample_df

    Name  Age
0   Jack   10
1   Jill   11
2  Harry   12
3    Vin   13
4   Jake   14
5   Jake   14
6   Jake   14

In [19]:
sample_df.duplicated().sum()

2

In [20]:
sample_df.drop_duplicates(inplace=True)

In [21]:
sample_df.duplicated().sum()

0

In [22]:
sample_df

    Name  Age
0   Jack   10
1   Jill   11
2  Harry   12
3    Vin   13
4   Jake   14

In [23]:
so_data.isnull()

,ResponseId,MainBranch,Employment,Country,US_State,UK_Country,EdLevel,Age1stCode,LearnCode,YearsCode,...,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,SurveyLength,SurveyEase,ConvertedCompYearly
0,False,False,False,False,True,True,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,True,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
2,False,False,False,False,True,True,False,False,False,True,...,False,False,False,False,False,False,False,False,False,True
3,False,False,False,False,True,True,False,False,True,True,...,False,False,False,False,False,False,True,False,False,True
4,False,False,False,False,True,False,False,False,False,False,...,False,False,False,True,False,False,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83434,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
83435,False,False,False,False,True,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
83436,False,False,False,False,False,True,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
83437,False,False,False,False,True,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
83438,False,False,False,False,True,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [24]:
so_data.isnull().sum()

ResponseId                          0
MainBranch                          0
Employment                        116
Country                             0
US_State                        68519
UK_Country                      79021
EdLevel                           313
Age1stCode                        196
LearnCode                         476
YearsCode                        1798
YearsCodePro                    22223
DevType                         16955
OrgSize                         22713
Currency                        22359
CompTotal                       36256
CompFreq                        31289
LanguageHaveWorkedWith           1082
LanguageWantToWorkWith           6618
DatabaseHaveWorkedWith          13893
DatabaseWantToWorkWith          25140
PlatformHaveWorkedWith          31304
PlatformWantToWorkWith          41820
WebframeHaveWorkedWith          21732
WebframeWantToWorkWith          31344
MiscTechHaveWorkedWith          36384
MiscTechWantToWorkWith          45418
ToolsTechHaveWorkedWith         10902
ToolsTechWantToWorkWith         17959
NEWCollabToolsHaveWorkedWith     2205
NEWCollabToolsWantToWorkWith    10417
OpSys                             145
NEWStuck                          387
NEWSOSites                        268
SOVisitFreq                      1026
SOAccount                         914
SOPartFreq                      15886
SOComm                           1120
NEWOtherComms                     611
Age                              1032
Gender                           1153
Trans                            2761
Sexuality                       10073
Ethnicity                        3975
Accessibility                    5836
MentalHealth                     6519
SurveyLength                     1728
SurveyEase                       1491
ConvertedCompYearly             36595
dtype: int64

In [25]:
so_data.isnull()

,ResponseId,MainBranch,Employment,Country,US_State,UK_Country,EdLevel,Age1stCode,LearnCode,YearsCode,...,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,SurveyLength,SurveyEase,ConvertedCompYearly
0,False,False,False,False,True,True,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,True,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
2,False,False,False,False,True,True,False,False,False,True,...,False,False,False,False,False,False,False,False,False,True
3,False,False,False,False,True,True,False,False,True,True,...,False,False,False,False,False,False,True,False,False,True
4,False,False,False,False,True,False,False,False,False,False,...,False,False,False,True,False,False,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83434,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
83435,False,False,False,False,True,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
83436,False,False,False,False,False,True,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
83437,False,False,False,False,True,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
83438,False,False,False,False,True,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [26]:
so_data.columns

Index(['ResponseId', 'MainBranch', 'Employment', 'Country', 'US_State',
       'UK_Country', 'EdLevel', 'Age1stCode', 'LearnCode', 'YearsCode',
       'YearsCodePro', 'DevType', 'OrgSize', 'Currency', 'CompTotal',
       'CompFreq', 'LanguageHaveWorkedWith', 'LanguageWantToWorkWith',
       'DatabaseHaveWorkedWith', 'DatabaseWantToWorkWith',
       'PlatformHaveWorkedWith', 'PlatformWantToWorkWith',
       'WebframeHaveWorkedWith', 'WebframeWantToWorkWith',
       'MiscTechHaveWorkedWith', 'MiscTechWantToWorkWith',
       'ToolsTechHaveWorkedWith', 'ToolsTechWantToWorkWith',
       'NEWCollabToolsHaveWorkedWith', 'NEWCollabToolsWantToWorkWith', 'OpSys',
       'NEWStuck', 'NEWSOSites', 'SOVisitFreq', 'SOAccount', 'SOPartFreq',
       'SOComm', 'NEWOtherComms', 'Age', 'Gender', 'Trans', 'Sexuality',
       'Ethnicity', 'Accessibility', 'MentalHealth', 'SurveyLength',
       'SurveyEase', 'ConvertedCompYearly'],
      dtype='object')

In [27]:
so_data.drop(['CompTotal'], axis=1, inplace=True)

In [32]:
so_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83439 entries, 0 to 83438
Data columns (total 47 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   ResponseId                    83439 non-null  int64
 1   MainBranch                    83439 non-null  object
 2   Employment                    83323 non-null  object
 3   Country                       83439 non-null  object
 4   US_State                      14920 non-null  object
 5   UK_Country                    4418 non-null   object
 6   EdLevel                       83126 non-null  object
 7   Age1stCode                    83243 non-null  object
 8   LearnCode                     82963 non-null  object
 9   YearsCode                     81641 non-null  object
 10  YearsCodePro                  61216 non-null  object
 11  DevType                       66484 non-null  object
 12  OrgSize                       60726 non-null  object
 13  Currency                      61080 non-null  object
 14  CompFreq                      52150 non-null  object
 15  LanguageHaveWorkedWith        82357 non-null  object
 16  LanguageWantToWorkWith        76821 non-null  object
 17  DatabaseHaveWorkedWith        69546 non-null  object
 18  DatabaseWantToWorkWith        58299 non-null  object
 19  PlatformHaveWorkedWith        52135 non-null  object
 20  PlatformWantToWorkWith        41619 non-null  object
 21  WebframeHaveWorkedWith        61707 non-null  object
 22  WebframeWantToWorkWith        52095 non-null  object
 23  MiscTechHaveWorkedWith        47055 non-null  object
 24  MiscTechWantToWorkWith        38021 non-null  object
 25  ToolsTechHaveWorkedWith       72537 non-null  object
 26  ToolsTechWantToWorkWith       65480 non-null  object
 27  NEWCollabToolsHaveWorkedWith  81234 non-null  object
 28  NEWCollabToolsWantToWorkWith  73022 non-null  object
 29  OpSys                         83294 non-null  object
 30  NEWStuck                      83052 non-null  object
 31  NEWSOSites                    83171 non-null  object
 32  SOVisitFreq                   82413 non-null  object
 33  SOAccount                     82525 non-null  object
 34  SOPartFreq                    67553 non-null  object
 35  SOComm                        82319 non-null  object
 36  NEWOtherComms                 82828 non-null  object
 37  Age                           82407 non-null  object
 38  Gender                        82286 non-null  object
 39  Trans                         80678 non-null  object
 40  Sexuality                     73366 non-null  object
 41  Ethnicity                     79464 non-null  object
 42  Accessibility                 77603 non-null  object
 43  MentalHealth                  76920 non-null  object
 44  SurveyLength                  81711 non-null  object
 45  SurveyEase                    81948 non-null  object
 46  ConvertedCompYearly           46844 non-null  float64
dtypes: float64(1), int64(1), object(45)
memory usage: 29.9+ MB

In [33]:
so_data.columns

Index(['ResponseId', 'MainBranch', 'Employment', 'Country', 'US_State',
       'UK_Country', 'EdLevel', 'Age1stCode', 'LearnCode', 'YearsCode',
       'YearsCodePro', 'DevType', 'OrgSize', 'Currency', 'CompFreq',
       'LanguageHaveWorkedWith', 'LanguageWantToWorkWith',
       'DatabaseHaveWorkedWith', 'DatabaseWantToWorkWith',
       'PlatformHaveWorkedWith', 'PlatformWantToWorkWith',
       'WebframeHaveWorkedWith', 'WebframeWantToWorkWith',
       'MiscTechHaveWorkedWith', 'MiscTechWantToWorkWith',
       'ToolsTechHaveWorkedWith', 'ToolsTechWantToWorkWith',
       'NEWCollabToolsHaveWorkedWith', 'NEWCollabToolsWantToWorkWith', 'OpSys',
       'NEWStuck', 'NEWSOSites', 'SOVisitFreq', 'SOAccount', 'SOPartFreq',
       'SOComm', 'NEWOtherComms', 'Age', 'Gender', 'Trans', 'Sexuality',
       'Ethnicity', 'Accessibility', 'MentalHealth', 'SurveyLength',
       'SurveyEase', 'ConvertedCompYearly'],
      dtype='object')

In [37]:
so_data['Employment'].isnull().sum()

116

In [38]:
so_data['Employment'].nunique()

9

In [39]:
so_data['Employment'].unique()

array(['Independent contractor, freelancer, or self-employed',
       'Student, full-time', 'Employed full-time', 'Student, part-time',
       'I prefer not to say', 'Employed part-time',
       'Not employed, but looking for work', 'Retired',
       'Not employed, and not looking for work', nan], dtype=object)

In [42]:
so_data['Employment'].value_counts()

Employed full-time                                      53584
Student, full-time                                      11781
Independent contractor, freelancer, or self-employed     8041
Not employed, but looking for work                       2961
Employed part-time                                       2461
Student, part-time                                       2051
Not employed, and not looking for work                   1228
I prefer not to say                                       890
Retired                                                   326
Name: Employment, dtype: int64

In [43]:
so_data['Employment'].fillna(so_data['Employment'].mode, inplace=True)

In [44]:
so_data['Employment'].isnull().sum()

0

In [46]:
so_data['Currency'].isnull().sum()

22359

In [47]:
so_data['Currency'].unique()

array(['EUR European Euro', nan, 'GBP\tPound sterling',
       'INR\tIndian rupee', 'SEK\tSwedish krona', 'TRY\tTurkish lira',
       'CAD\tCanadian dollar', 'SGD\tSingapore dollar',
       'CHF\tSwiss franc', 'RUB\tRussian ruble',
       'ILS\tIsraeli new shekel', 'USD\tUnited States dollar',
       'BRL\tBrazilian real', 'BGN\tBulgarian lev',
       'AED United Arab Emirates dirham', 'PLN\tPolish zloty',
       'UZS\tUzbekistani som', 'HUF\tHungarian forint',
       'PKR\tPakistani rupee', 'ZMW Zambian kwacha',
       'NGN\tNigerian naira', 'ALL\tAlbanian lek',
       'BDT\tBangladeshi taka', 'IRR\tIranian rial', 'RON\tRomanian leu',
       'HRK\tCroatian kuna', 'GEL\tGeorgian lari', 'DKK\tDanish krone',
       'AMD\tArmenian dram', 'LBP\tLebanese pound', 'BHD\tBahraini dinar',
       'EGP\tEgyptian pound', 'AUD\tAustralian dollar',
       'CLP\tChilean peso', 'IDR\tIndonesian rupiah',
       'RSD\tSerbian dinar', 'KRW\tSouth Korean won',
       'HKD\tHong Kong dollar', 'NPR\tNepalese rupee',
       'UAH\tUkrainian hryvnia', 'JPY\tJapanese yen',
       'TZS\tTanzanian shilling', 'PEN\tPeruvian sol',
       'BOB\tBolivian boliviano', 'CZK\tCzech koruna',
       'ZAR\tSouth African rand', 'ARS\tArgentine peso',
       'NOK\tNorwegian krone', 'VND\tVietnamese dong',
       'MYR\tMalaysian ringgit', 'MGA\tMalagasy ariary',
       'KES\tKenyan shilling', 'LKR\tSri Lankan rupee',
       'TND\tTunisian dinar', 'BYN\tBelarusian ruble',
       'COP\tColombian peso', 'MKD\tMacedonian denar',
       'BWP\tBotswana pula', 'DZD\tAlgerian dinar',
       'BAM\tBosnia and Herzegovina convertible mark',
       'CNY\tChinese Yuan Renminbi', 'MXN\tMexican peso',
       'MAD\tMoroccan dirham', 'JOD\tJordanian dinar',
       'DOP\tDominican peso', 'THB\tThai baht', 'ETB\tEthiopian birr',
       'XOF\tWest African CFA franc', 'PYG\tParaguayan guarani',
       'ISK\tIcelandic krona', 'HTG\tHaitian gourde',
       'TWD\tNew Taiwan dollar', 'GTQ\tGuatemalan quetzal',
       'XAF\tCentral African CFA franc', 'KZT\tKazakhstani tenge',
       'LYD\tLibyan dinar', 'CUP\tCuban peso', 'SYP\tSyrian pound',
       'PHP\tPhilippine peso', 'XCD\tEast Caribbean dollar',
       'LAK\tLao kip', 'YER\tYemeni rial', 'TOP\tTongan pa’anga',
       'IQD\tIraqi dinar', 'CRC\tCosta Rican colon',
       'MRU\tMauritanian ouguiya', 'AZN\tAzerbaijan manat',
       'SAR\tSaudi Arabian riyal', 'AOA\tAngolan kwanza',
       'SDG\tSudanese pound', 'GYD\tGuyanese dollar', 'XPF\tCFP franc',
       'NZD\tNew Zealand dollar', 'UYU\tUruguayan peso',
       'HNL\tHonduran lempira', 'NIO\tNicaraguan cordoba',
       'MZN\tMozambican metical', 'TTD\tTrinidad and Tobago dollar',
       'GHS\tGhanaian cedi', 'BBD\tBarbadian dollar',
       'FJD\tFijian dollar', 'VES\tVenezuelan bolivar',
       'UGX\tUgandan shilling', 'KWD\tKuwaiti dinar',
       'GMD\tGambian dalasi', 'LSL\tLesotho loti', 'MMK\tMyanmar kyat',
       'KGS\tKyrgyzstani som', 'AFN\tAfghan afghani',
       'MUR\tMauritian rupee', 'SZL\tSwazi lilangeni',
       'RWF\tRwandan franc', 'MDL\tMoldovan leu', 'TMT\tTurkmen manat',
       'KYD\tCayman Islands dollar', 'KHR\tCambodian riel',
       'IMP\tManx pound', 'QAR\tQatari riyal', 'BZD\tBelize dollar',
       'ANG Netherlands Antillean guilder', 'MNT\tMongolian tugrik',
       'TJS\tTajikistani somoni', 'OMR\tOmani rial', 'BIF\tBurundi franc',
       'JMD\tJamaican dollar', 'NAD\tNamibian dollar',
       'GNF\tGuinean franc', 'none\tCook Islands dollar',
       'CDF\tCongolese franc', 'PGK\tPapua New Guinean kina',
       'LRD\tLiberian dollar', 'MVR\tMaldivian rufiyaa',
       'GIP\tGibraltar pound', 'BSD\tBahamian dollar',
       'AWG\tAruban florin', 'DJF\tDjiboutian franc',
       'SHP\tSaint Helena pound', 'MWK\tMalawian kwacha',
       'BTN\tBhutanese ngultrum', 'SRD\tSurinamese dollar',
       'VUV\tVanuatu vatu', 'CVE\tCape Verdean escudo',
       'BMD\tBermudian dollar', 'GGP\tGuernsey Pound',
       'KPW\tNorth Korean won', 'XDR\tSDR (Special Drawing Right)',
       'ERN\tEritrean nakfa'], dtype=object)

In [48]:
so_data.describe()

         ResponseId  ConvertedCompYearly
count  83439.000000         4.684400e+04
mean   41720.000000         1.184262e+05
std    24086.908893         5.272944e+05
min        1.000000         1.000000e+00
25%    20860.500000         2.702500e+04
50%    41720.000000         5.621100e+04
75%    62579.500000         1.000000e+05
max    83439.000000         4.524131e+07

In [59]:
so_data.sample(5)

,ResponseId,MainBranch,Employment,Country,US_State,UK_Country,EdLevel,Age1stCode,LearnCode,YearsCode,...,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,SurveyLength,SurveyEase,ConvertedCompYearly
24240,24241,I am a developer by profession,Employed full-time,Belgium,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",20,...,35-44 years old,Man,No,Prefer not to say,White or of European descent,None of the above,None of the above,Too long,Easy,54049.0
83242,83243,I am a developer by profession,Employed full-time,United States of America,Iowa,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,School;Books / Physical media,7,...,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,Prefer not to say,Appropriate in length,Easy,92000.0
30682,30683,I am a developer by profession,Employed full-time,South Korea,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",25 - 34 years,Coding Bootcamp;Online Courses or Certificatio...,5,...,25-34 years old,Man,No,Straight / Heterosexual,East Asian,None of the above,None of the above,Appropriate in length,Easy,26160.0
23199,23200,I am a student who is learning to code,"Student, full-time",Greece,NaN,NaN,Something else,18 - 24 years,"Other online resources (ex: videos, blogs, etc...",5,...,18-24 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Neither easy nor difficult,NaN
14066,14067,I am a developer by profession,Employed full-time,Bulgaria,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",18 - 24 years,Coding Bootcamp;Other online resources (ex: vi...,2,...,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,5964.0

In [62]:
so_data.nlargest(5,'Responseld')

KeyError: 'Responseld'

In [66]:
so_data.groupby('Country').get_group('South Korea')

,ResponseId,MainBranch,Employment,Country,US_State,UK_Country,EdLevel,Age1stCode,LearnCode,YearsCode,...,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,SurveyLength,SurveyEase,ConvertedCompYearly
549,550,"I am not primarily a developer, but I write co...",Employed full-time,South Korea,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",35 - 44 years,Coding Bootcamp,4,...,35-44 years old,Man,No,Straight / Heterosexual,East Asian,None of the above,I have a concentration and/or memory disorder ...,Appropriate in length,Easy,NaN
685,686,I am a student who is learning to code,"Student, full-time",South Korea,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",18 - 24 years,"Other online resources (ex: videos, blogs, etc...",NaN,...,18-24 years old,Man,No,Straight / Heterosexual,East Asian,None of the above,None of the above,Too short,Easy,NaN
1430,1431,I am a developer by profession,Employed full-time,South Korea,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",5 - 10 years,NaN,10,...,25-34 years old,Man,No,Straight / Heterosexual;Prefer to self-describe:,White or of European descent;I don't know,None of the above,None of the above,Appropriate in length,Easy,40248.0
1862,1863,I am a developer by profession,Employed full-time,South Korea,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,Other (please specify):,14,...,35-44 years old,Man,No,Straight / Heterosexual,East Asian,None of the above,None of the above,Appropriate in length,Easy,39201.0
5917,5918,I am a student who is learning to code,"Student, full-time",South Korea,NaN,NaN,"Secondary school (e.g. American high school, G...",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",10,...,18-24 years old,Man,No,NaN,East Asian,None of the above,None of the above,Appropriate in length,Neither easy nor difficult,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81582,81583,None of these,"Student, full-time",South Korea,NaN,NaN,"Other doctoral degree (Ph.D., Ed.D., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",17,...,25-34 years old,Man,No,NaN,East Asian,None of the above,None of the above,Appropriate in length,Easy,NaN
82036,82037,I am a student who is learning to code,"Student, full-time",South Korea,NaN,NaN,"Secondary school (e.g. American high school, G...",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",5,...,Under 18 years old,Man,No,Straight / Heterosexual,East Asian,None of the above,None of the above,Appropriate in length,Easy,NaN
82096,82097,I am a developer by profession,Employed full-time,South Korea,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,School,23,...,35-44 years old,Man,No,Straight / Heterosexual,East Asian,None of the above,None of the above,Appropriate in length,Easy,NaN
83366,83367,I am a developer by profession,Employed full-time,South Korea,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",18 - 24 years,Coding Bootcamp;Other online resources (ex: vi...,10,...,25-34 years old,Man,No,Straight / Heterosexual,East Asian,None of the above,None of the above,Appropriate in length,Easy,NaN
83402,83403,I am a developer by profession,Employed full-time,South Korea,NaN,NaN,"Secondary school (e.g. American high school, G...",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",4,...,18-24 years old,Woman,No,Bisexual,East Asian,None of the above,None of the above,Appropriate in length,Easy,18708.0

In [73]:
so_data_new = so_data.loc[1:1000]

In [69]:
so_data_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 1 to 1000
Data columns (total 47 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   ResponseId                    1000 non-null   int64
 1   MainBranch                    1000 non-null   object
 2   Employment                    1000 non-null   object
 3   Country                       1000 non-null   object
 4   US_State                      152 non-null    object
 5   UK_Country                    75 non-null     object
 6   EdLevel                       993 non-null    object
 7   Age1stCode                    998 non-null    object
 8   LearnCode                     982 non-null    object
 9   YearsCode                     939 non-null    object
 10  YearsCodePro                  738 non-null    object
 11  DevType                       797 non-null    object
 12  OrgSize                       749 non-null    object
 13  Currency                      751 non-null    object
 14  CompFreq                      654 non-null    object
 15  LanguageHaveWorkedWith        987 non-null    object
 16  LanguageWantToWorkWith        922 non-null    object
 17  DatabaseHaveWorkedWith        809 non-null    object
 18  DatabaseWantToWorkWith        671 non-null    object
 19  PlatformHaveWorkedWith        596 non-null    object
 20  PlatformWantToWorkWith        450 non-null    object
 21  WebframeHaveWorkedWith        705 non-null    object
 22  WebframeWantToWorkWith        602 non-null    object
 23  MiscTechHaveWorkedWith        583 non-null    object
 24  MiscTechWantToWorkWith        472 non-null    object
 25  ToolsTechHaveWorkedWith       865 non-null    object
 26  ToolsTechWantToWorkWith       768 non-null    object
 27  NEWCollabToolsHaveWorkedWith  973 non-null    object
 28  NEWCollabToolsWantToWorkWith  863 non-null    object
 29  OpSys                         999 non-null    object
 30  NEWStuck                      996 non-null    object
 31  NEWSOSites                    998 non-null    object
 32  SOVisitFreq                   997 non-null    object
 33  SOAccount                     998 non-null    object
 34  SOPartFreq                    969 non-null    object
 35  SOComm                        993 non-null    object
 36  NEWOtherComms                 997 non-null    object
 37  Age                           994 non-null    object
 38  Gender                        987 non-null    object
 39  Trans                         971 non-null    object
 40  Sexuality                     895 non-null    object
 41  Ethnicity                     956 non-null    object
 42  Accessibility                 937 non-null    object
 43  MentalHealth                  928 non-null    object
 44  SurveyLength                  986 non-null    object
 45  SurveyEase                    991 non-null    object
 46  ConvertedCompYearly           586 non-null    float64
dtypes: float64(1), int64(1), object(45)
memory usage: 367.3+ KB

In [74]:
so_data_new.loc[10:15]

,ResponseId,MainBranch,Employment,Country,US_State,UK_Country,EdLevel,Age1stCode,LearnCode,YearsCode,...,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,SurveyLength,SurveyEase,ConvertedCompYearly
10,11,I am a developer by profession,Employed full-time,United Kingdom of Great Britain and Northern I...,NaN,England,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc)",16,...,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,NaN
11,12,I am a developer by profession,Employed full-time,Spain,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",12,...,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent;Hispanic or Latin...,None of the above,None of the above,Too long,Easy,46482.0
12,13,I am a developer by profession,Employed full-time,Germany,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",11 - 17 years,Other (please specify):,15,...,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,Prefer not to say,Appropriate in length,Easy,77290.0
13,14,I am a student who is learning to code,Employed full-time,Peru,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",5 - 10 years,School,10,...,Prefer not to say,Prefer not to say,Prefer not to say,Prefer not to say,Prefer not to say,Prefer not to say,Prefer not to say,Too long,Neither easy nor difficult,NaN
14,15,"I used to be a developer by profession, but no...","Not employed, but looking for work",United Kingdom of Great Britain and Northern I...,NaN,England,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,School,40,...,45-54 years old,Man,No,Prefer not to say,Prefer not to say,None of the above,I have a mood or emotional disorder (e.g. depr...,Appropriate in length,Neither easy nor difficult,NaN
15,16,I am a student who is learning to code,"Student, full-time",United States of America,Missouri,NaN,"Secondary school (e.g. American high school, G...",5 - 10 years,Other (please specify):,7,...,Under 18 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,I have a concentration and/or memory disorder ...,Too long,Easy,NaN

In [75]:
so_data_new.loc[so_data_new.Country == 'Germany']

,ResponseId,MainBranch,Employment,Country,US_State,UK_Country,EdLevel,Age1stCode,LearnCode,YearsCode,...,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,SurveyLength,SurveyEase,ConvertedCompYearly
12,13,I am a developer by profession,Employed full-time,Germany,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",11 - 17 years,Other (please specify):,15,...,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,Prefer not to say,Appropriate in length,Easy,77290.0
20,21,I am a developer by profession,"Student, full-time",Germany,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,School;Colleague,NaN,...,25-34 years old,Man,No,NaN,White or of European descent,NaN,NaN,Too long,Easy,NaN
24,25,I am a developer by profession,Employed full-time,Germany,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",11 - 17 years,School;Friend or family member,26,...,35-44 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,77831.0
25,26,"I am not primarily a developer, but I write co...",Employed full-time,Germany,NaN,NaN,"Other doctoral degree (Ph.D., Ed.D., etc.)",25 - 34 years,Coding Bootcamp;Online Forum,12,...,35-44 years old,"Non-binary, genderqueer, or gender non-conforming",Prefer not to say,Bisexual,White or of European descent,None of the above,I have an anxiety disorder,Appropriate in length,Neither easy nor difficult,NaN
35,36,I am a developer by profession,Employed full-time,Germany,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",11 - 17 years,School;Online Forum;Other (please specify):,19,...,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,60535.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
960,961,None of these,"Student, full-time",Germany,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,School;Online Forum;Other (please specify):,9,...,25-34 years old,"Man;Non-binary, genderqueer, or gender non-con...",No,Straight / Heterosexual,White or of European descent,None of the above,I have a mood or emotional disorder (e.g. depr...,Appropriate in length,Easy,NaN
973,974,I am a developer by profession,I prefer not to say,Germany,NaN,NaN,"Secondary school (e.g. American high school, G...",18 - 24 years,Other (please specify):,30,...,45-54 years old,Man,No,Straight / Heterosexual,Biracial,None of the above,I have a mood or emotional disorder (e.g. depr...,Appropriate in length,Easy,NaN
975,976,I am a developer by profession,Employed full-time,Germany,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",35,...,45-54 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,81074.0
978,979,"I am not primarily a developer, but I write co...","Not employed, but looking for work",Germany,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",20,...,25-34 years old,Man,No,Straight / Heterosexual,Multiracial,None of the above,I have a concentration and/or memory disorder ...,Appropriate in length,Neither easy nor difficult,NaN
997,998,I am a developer by profession,Employed full-time,Germany,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",21,...,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,NaN,NaN,Appropriate in length,Easy,56211.0

In [80]:
so_data_new.iloc[[0,5,10,15]]

,ResponseId,MainBranch,Employment,Country,US_State,UK_Country,EdLevel,Age1stCode,LearnCode,YearsCode,...,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,SurveyLength,SurveyEase,ConvertedCompYearly
1,2,I am a student who is learning to code,"Student, full-time",Netherlands,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",7,...,18-24 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,NaN
6,7,I code primarily as a hobby,I prefer not to say,United States of America,New Hampshire,NaN,"Secondary school (e.g. American high school, G...",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",3,...,Prefer not to say,Prefer not to say,No,NaN,I don't know,None of the above,None of the above,Appropriate in length,Neither easy nor difficult,NaN
11,12,I am a developer by profession,Employed full-time,Spain,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",12,...,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent;Hispanic or Latin...,None of the above,None of the above,Too long,Easy,46482.0
16,17,I am a developer by profession,Employed full-time,Turkey,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",5 - 10 years,School,6,...,25-34 years old,Man,No,NaN,Middle Eastern,NaN,NaN,Appropriate in length,Neither easy nor difficult,17748.0

In [81]:
so_data_new2 = so_data.iloc[:1000]

In [82]:
so_data_new2.iloc[[0,5,10,15]]

,ResponseId,MainBranch,Employment,Country,US_State,UK_Country,EdLevel,Age1stCode,LearnCode,YearsCode,...,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,SurveyLength,SurveyEase,ConvertedCompYearly
0,1,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Slovakia,NaN,NaN,"Secondary school (e.g. American high school, G...",18 - 24 years,Coding Bootcamp;Other online resources (ex: vi...,NaN,...,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,62268.0
5,6,I am a student who is learning to code,"Student, part-time",United States of America,Georgia,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",NaN,...,18-24 years old,Prefer not to say,No,Straight / Heterosexual,Prefer not to say,None of the above,I have a concentration and/or memory disorder ...,Too long,Neither easy nor difficult,NaN
10,11,I am a developer by profession,Employed full-time,United Kingdom of Great Britain and Northern I...,NaN,England,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc)",16,...,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,NaN
15,16,I am a student who is learning to code,"Student, full-time",United States of America,Missouri,NaN,"Secondary school (e.g. American high school, G...",5 - 10 years,Other (please specify):,7,...,Under 18 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,I have a concentration and/or memory disorder ...,Too long,Easy,NaN

In [84]:
so_data_new2.iloc[:5, :5]

,ResponseId,MainBranch,Employment,Country,US_State
0,1,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Slovakia,NaN
1,2,I am a student who is learning to code,"Student, full-time",Netherlands,NaN
2,3,"I am not primarily a developer, but I write co...","Student, full-time",Russian Federation,NaN
3,4,I am a developer by profession,Employed full-time,Austria,NaN
4,5,I am a developer by profession,"Independent contractor, freelancer, or self-em...",United Kingdom of Great Britain and Northern I...,NaN

In [85]:
so_data_new2.iloc[2:5, :5]

,ResponseId,MainBranch,Employment,Country,US_State
2,3,"I am not primarily a developer, but I write co...","Student, full-time",Russian Federation,NaN
3,4,I am a developer by profession,Employed full-time,Austria,NaN
4,5,I am a developer by profession,"Independent contractor, freelancer, or self-em...",United Kingdom of Great Britain and Northern I...,NaN

In [86]:
so_data_new2.iloc[2:5, 2:5]

,Employment,Country,US_State
2,"Student, full-time",Russian Federation,NaN
3,Employed full-time,Austria,NaN
4,"Independent contractor, freelancer, or self-em...",United Kingdom of Great Britain and Northern I...,NaN

In [87]:
so_data_new2.loc[2:5]

,ResponseId,MainBranch,Employment,Country,US_State,UK_Country,EdLevel,Age1stCode,LearnCode,YearsCode,...,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,SurveyLength,SurveyEase,ConvertedCompYearly
2,3,"I am not primarily a developer, but I write co...","Student, full-time",Russian Federation,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",NaN,...,18-24 years old,Man,No,Prefer not to say,Prefer not to say,None of the above,None of the above,Appropriate in length,Easy,NaN
3,4,I am a developer by profession,Employed full-time,Austria,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",11 - 17 years,NaN,NaN,...,35-44 years old,Man,No,Straight / Heterosexual,White or of European descent,I am deaf / hard of hearing,NaN,Appropriate in length,Neither easy nor difficult,NaN
4,5,I am a developer by profession,"Independent contractor, freelancer, or self-em...",United Kingdom of Great Britain and Northern I...,NaN,England,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",5 - 10 years,Friend or family member,17,...,25-34 years old,Man,No,NaN,White or of European descent,None of the above,NaN,Appropriate in length,Easy,NaN
5,6,I am a student who is learning to code,"Student, part-time",United States of America,Georgia,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",NaN,...,18-24 years old,Prefer not to say,No,Straight / Heterosexual,Prefer not to say,None of the above,I have a concentration and/or memory disorder ...,Too long,Neither easy nor difficult,NaN

In [88]:
so_data_new2.iloc[2:5]

,ResponseId,MainBranch,Employment,Country,US_State,UK_Country,EdLevel,Age1stCode,LearnCode,YearsCode,...,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,SurveyLength,SurveyEase,ConvertedCompYearly
2,3,"I am not primarily a developer, but I write co...","Student, full-time",Russian Federation,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",NaN,...,18-24 years old,Man,No,Prefer not to say,Prefer not to say,None of the above,None of the above,Appropriate in length,Easy,NaN
3,4,I am a developer by profession,Employed full-time,Austria,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",11 - 17 years,NaN,NaN,...,35-44 years old,Man,No,Straight / Heterosexual,White or of European descent,I am deaf / hard of hearing,NaN,Appropriate in length,Neither easy nor difficult,NaN
4,5,I am a developer by profession,"Independent contractor, freelancer, or self-em...",United Kingdom of Great Britain and Northern I...,NaN,England,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",5 - 10 years,Friend or family member,17,...,25-34 years old,Man,No,NaN,White or of European descent,None of the above,NaN,Appropriate in length,Easy,NaN

In [92]:
so_data_new2[['Empolyment','Country','Age','Gender']].sort_values(by='Age')

KeyError: "['Empolyment'] not in index"

In [94]:
so_data_new2.query('Age < 23 and Gender == "Woman" '')

SyntaxError: EOL while scanning string literal (2634159758.py, line 1)

In [96]:
so_data_new2.to_csv('Reduced StackOverflow data.csv', index=False)

In [97]:
so_data_new2.to_excel('Reduced StackOverflow data sheet.xlsx', sheet_name='New Data')